[[articles]]
title = "Example article"
description = "Example description of an article."
icon = "vial"
sections = ["Overview of Interactions"]
url_param = "example-article"
path = "example_article.md"
