[[articles]]
title = "What is Marvo?"
description = "Discover how Marvo can transform your server."
url_param = "what-is-marvo"
path = "what_is_marvo.md"

[[articles]]
title = "Setup & Onboarding"
description = "Get Marvo up and running in your server."
url_param = "setup-and-onboarding"
path = "setup_and_onboarding.md"

[[articles]]
title = "Plugin Overview"
description = "Explore the plugins Marvo has to offer."
url_param = "plugin-overview"
path = "plugin_overview.md"
